2025-06-30 15:36:45.453993 - User: AnonymousUser - Path: /
Not Found: /
2025-06-30 15:36:47.801631 - User: AnonymousUser - Path: /favicon.ico
Not Found: /favicon.ico
2025-06-30 15:36:55.708493 - User: AnonymousUser - Path: /admin/
2025-06-30 15:36:55.751231 - User: AnonymousUser - Path: /admin/login/
2025-06-30 15:37:14.774785 - User: AnonymousUser - Path: /admin/login/
2025-06-30 15:37:16.691125 - User: kimongi - Path: /admin/
2025-06-30 15:37:40.453958 - User: kimongi - Path: /admin/auth/user/4/change/
2025-06-30 15:37:40.657209 - User: kimongi - Path: /admin/jsi18n/
2025-06-30 15:37:57.956238 - User: kimongi - Path: /
Not Found: /
2025-06-30 15:38:05.228105 - User: kimongi - Path: /api/
2025-06-30 15:38:12.679598 - User: kimongi - Path: /api/conversations/
2025-06-30 15:38:20.350057 - User: kimongi - Path: /api/conversations/
Bad Request: /api/conversations/
2025-06-30 15:38:22.763643 - User: kimongi - Path: /api/conversations/
Bad Request: /api/conversations/
2025-06-30 15:38:39.152771 - User: kimongi - Path: /api/conversations/
2025-06-30 15:39:00.908455 - User: kimongi - Path: /api/conversations/
2025-06-30 15:39:18.304772 - User: kimongi - Path: /api/conversations/
Bad Request: /api/conversations/
2025-06-30 15:39:24.593168 - User: kimongi - Path: /api/conversations/
2025-06-30 15:39:36.274730 - User: kimongi - Path: /api/
2025-06-30 15:39:39.199283 - User: kimongi - Path: /api/messages/
Internal Server Error: /api/messages/
Traceback (most recent call last):
  File "/home/kimongi/code/alx/alx-backend-python/messaging_app/env/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kimongi/code/alx/alx-backend-python/messaging_app/env/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kimongi/code/alx/alx-backend-python/messaging_app/env/lib/python3.12/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kimongi/code/alx/alx-backend-python/messaging_app/env/lib/python3.12/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kimongi/code/alx/alx-backend-python/messaging_app/env/lib/python3.12/site-packages/rest_framework/views.py", line 515, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kimongi/code/alx/alx-backend-python/messaging_app/env/lib/python3.12/site-packages/rest_framework/views.py", line 475, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/kimongi/code/alx/alx-backend-python/messaging_app/env/lib/python3.12/site-packages/rest_framework/views.py", line 486, in raise_uncaught_exception
    raise exc
  File "/home/kimongi/code/alx/alx-backend-python/messaging_app/env/lib/python3.12/site-packages/rest_framework/views.py", line 512, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kimongi/code/alx/alx-backend-python/messaging_app/env/lib/python3.12/site-packages/rest_framework/mixins.py", line 38, in list
    queryset = self.filter_queryset(self.get_queryset())
                                    ^^^^^^^^^^^^^^^^^^^
  File "/home/kimongi/code/alx/alx-backend-python/Django-Middleware-0x03/chats/views.py", line 38, in get_queryset
    return Message.objects.filter(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kimongi/code/alx/alx-backend-python/messaging_app/env/lib/python3.12/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kimongi/code/alx/alx-backend-python/messaging_app/env/lib/python3.12/site-packages/django/db/models/query.py", line 1493, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kimongi/code/alx/alx-backend-python/messaging_app/env/lib/python3.12/site-packages/django/db/models/query.py", line 1511, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/home/kimongi/code/alx/alx-backend-python/messaging_app/env/lib/python3.12/site-packages/django/db/models/query.py", line 1518, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/home/kimongi/code/alx/alx-backend-python/messaging_app/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1646, in add_q
    clause, _ = self._add_q(q_object, can_reuse)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kimongi/code/alx/alx-backend-python/messaging_app/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1678, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/home/kimongi/code/alx/alx-backend-python/messaging_app/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1563, in build_filter
    self.check_related_objects(join_info.final_field, value, join_info.opts)
  File "/home/kimongi/code/alx/alx-backend-python/messaging_app/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1372, in check_related_objects
    self.check_query_object_type(value, opts, field)
  File "/home/kimongi/code/alx/alx-backend-python/messaging_app/env/lib/python3.12/site-packages/django/db/models/sql/query.py", line 1349, in check_query_object_type
    raise ValueError(
ValueError: Cannot query "kimongi": Must be "User" instance.
2025-06-30 15:40:20.681750 - User: kimongi - Path: /
Not Found: /
2025-06-30 15:40:28.751514 - User: kimongi - Path: /admin/
2025-06-30 15:40:36.829759 - User: kimongi - Path: /admin/auth/user/
2025-06-30 15:40:36.951868 - User: kimongi - Path: /admin/jsi18n/
2025-06-30 15:40:46.403020 - User: kimongi - Path: /admin/auth/user/add/
2025-06-30 15:40:46.526691 - User: kimongi - Path: /admin/jsi18n/
2025-06-30 15:41:01.635732 - User: kimongi - Path: /admin/auth/user/add/
2025-06-30 15:41:03.214543 - User: kimongi - Path: /admin/auth/user/5/change/
2025-06-30 15:41:03.425774 - User: kimongi - Path: /admin/jsi18n/
2025-06-30 15:46:06.214513 - User: AnonymousUser - Path: /api/token/
/home/kimongi/code/alx/alx-backend-python/Django-Middleware-0x03/chats/middleware.py changed, reloading.
/home/kimongi/code/alx/alx-backend-python/Django-Middleware-0x03/messaging_app/settings.py changed, reloading.
/home/kimongi/code/alx/alx-backend-python/Django-Middleware-0x03/messaging_app/settings.py changed, reloading.
/home/kimongi/code/alx/alx-backend-python/Django-Middleware-0x03/chats/middleware.py changed, reloading.
